workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    scripts:
      - name: Get Flutter packages  
        script: |
          cd . && flutter packages pub get
      - name: Build APK with Flutter  
        script: |
          cd . && flutter build apk --release --flavor prod
      - name: send apk to telegram channel  
        script: |
          curl -F chat_id="-1001937005377" -F document=@"build\app\outputs\flutter-apk\app-release.apk" "https://api.telegram.org/bot7028718106:AAEGppBRRM_kdzivMWZT5ZGUnSi7gtpYSlk/sendDocument"
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
 