name: magenta
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  bot_toast: ^4.1.3
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  dio: ^5.4.2+1
  easy_localization: ^3.0.5
  dartz: ^0.10.1
  firebase_core: ^3.1.0
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.0.0
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  get_it: ^7.6.8
  auto_route: ^8.0.2
  injectable: ^2.4.1
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  path: ^1.9.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timezone: ^0.9.2
  logger: ^2.2.0
  intl: ^0.19.0
  uuid: ^4.3.3
  json_serializable: ^6.7.1
  flutter_form_builder: ^9.2.1
  flutter_gen: ^5.4.0
  dropdown_button2: ^2.3.9
  just_the_tooltip: ^0.0.12
  flutter_image_compress: ^2.2.0
  image_cropper: ^7.0.5
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1
  form_builder_validators: ^10.0.1
  pinput: ^5.0.0
  lottie: ^3.1.0
  modal_bottom_sheet: ^3.0.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  loader_overlay: ^4.0.0
  google_sign_in: ^6.2.1
  flutter_blurhash: ^0.8.2
  firebase_auth: ^5.1.0
  sms_autofill: ^2.3.1
  url_launcher: ^6.2.6
  fluttertoast: ^8.2.4
  smooth_page_indicator: ^1.1.0
  sliver_tools: ^0.2.12


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  import_sorter: ^4.6.0
  flutter_gen_runner: ^5.3.2
  injectable_generator: ^2.4.1
  change_app_package_name: ^1.1.0
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  auto_route_generator: ^8.0.0
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Praise
      fonts:
        - asset: assets/fonts/Praise.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 600
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 400


