// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// 📦 Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

// 🌎 Project imports:
import 'package:magenta/config/common/environment_variables.dart';

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: EnvironmentVariables.apiKey,
    appId: EnvironmentVariables.appID,
    messagingSenderId: '836729890591',
    projectId: EnvironmentVariables.projectId,
    storageBucket: EnvironmentVariables.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: EnvironmentVariables.iosApiKey,
    appId: EnvironmentVariables.iosAppId,
    messagingSenderId: '836729890591',
    projectId: EnvironmentVariables.projectId,
    storageBucket: EnvironmentVariables.storageBucket,
    iosBundleId: EnvironmentVariables.iosBundleId,
  );

}
