name: core
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_svg: ^2.0.9
  responsive_builder: ^0.7.0
  flutter_screenutil: ^5.9.0
  auto_size_text: ^3.0.0
  either_dart: ^1.0.0
  file_picker: ^8.0.6
  dio: ^5.3.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.19.0
  marquee: ^2.2.3
  text_scroll: ^0.2.0
  uuid: ^4.2.1
  infinite_scroll_pagination: ^4.0.0
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  flutter_form_builder: ^9.1.1
  flutter_gen: ^5.3.2
  dropdown_button2: ^2.3.9
  just_the_tooltip: ^0.0.12

  #?################# Image handling
  flutter_image_compress: ^2.1.0
  image_cropper: ^7.0.5
  image_picker: ^1.0.4
  flutter_blurhash: ^0.8.2
  mime: ^1.0.4 # for file type lookup
  path_provider: ^2.1.1
  logger: ^2.0.2+1
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.4.0
# router
  auto_route: ^8.0.2  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2

flutter:
  uses-material-design: true
  generate: true # Add this line

  assets:
    - assets/icons/
    - assets/flags/
