name: Production App Store

on:
  push:
    branches: ["release/old-staging"]

jobs:
  build_and_deploy:
    runs-on: macos-15
    timeout-minutes: 30

    permissions:
      contents: read
      actions: read

    env:
      FLUTTER_VERSION: 3.24.0

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          ref: "release/old-staging"
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: pod install
        run: |
          cd ios
          pod install --repo-update
          cd ..

      # - name: Analyze to check for bad Dart/Flutter practices
      #   run: flutter analyze

      - name: Import certs
        uses: apple-actions/import-codesign-certs@v5
        with:
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}

      - name: Download provisioning profiles
        uses: apple-actions/download-provisioning-profiles@v4
        with:
          bundle-id: ${{ secrets.IOS_APP_PACKAGE_NAME }}
          issuer-id: ${{ secrets.APPSTORE_API_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Generate ExportOptions
        run: |
          cat <<EOF > ios/ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store-connect</string>
              <key>teamID</key>
              <string>${{ secrets.APPSTORE_TEAM_ID }}</string>
              <key>signingStyle</key>
              <string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
            <key>${{ secrets.IOS_APP_PACKAGE_NAME }}</key>
            <string>${{ secrets.APPSTORE_PROVISIONING_PROFILE_NAME }}</string>
              </dict>
          </dict>
          </plist>
          EOF

      - name: Build App
        run: |
          flutter build ipa --release --export-options-plist=ios/ExportOptions.plist --flavor production -t lib/main_production.dart
          echo "APP_FILE=$(basename $(ls build/ios/ipa/*.ipa))" >> $GITHUB_ENV

      - name: Upload generated ipa to the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_FILE }}
          path: build/ios/ipa/${{ env.APP_FILE }}
          retention-days: 7

      - name: Decode App Store API key
        run: |
          mkdir private_keys
          echo "${{ secrets.APPSTORE_API_PRIVATE_KEY }}" > private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8

      - name: Upload app to TestFlight
        run: |
          xcrun altool --upload-app \
          --output-format json \
          --file build/ios/ipa/${{ env.APP_FILE }} \
          --type ios \
          --apiKey ${{ secrets.APPSTORE_API_KEY_ID }} \
          --apiIssuer ${{ secrets.APPSTORE_API_ISSUER_ID }}

      - name: Extract App Version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //')
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: 📢 Notify ClickUp
        uses: architweb/ClickUpNotification@v1.4.0
        with:
          clickup_api_token: ${{ secrets.CLICKUP_API_TOKEN }}
          clickup_workspace_id: ${{ secrets.CLICKUP_WORKSPACE_ID }}
          clickup_channel_id: ${{ secrets.CLICKUP_CHANNEL_ID }}
          clickup_project_name: "${{ secrets.CLICKUP_PROJECT_NAME_APP_STORE }} - _v${{ env.APP_VERSION }}_"
